nightswatch:
  channel: '#nightswatch'
  members:
    - carlescere
    - memosstilvi
    - michaelkyriacou
    - cosenal
tag:
  channel: '#khaleesi-tag'
  members:
    - anafuiorea
    - eddking
    - marcindobry
    - willfrew
